# [en] Get your chat_id with the @userinfobot (send /start)
# [pt_br] Pegue o chat_id com o @userinfobot (envie /start)
# For 2 devices(Telegram) | chat_ids: ["YOUR_CHAT_ID_1", "YOUR_CHAT_ID_2"]
chat_ids: ["YOUR_CHAT_ID_1", "YOUR_CHAT_ID_2"]

# [en] Get your token with the @botfather: https://t.me/botfather (send /newbot)
# [pt_br] Pegue o token com o @botfather: https://t.me/botfather (envie /newbot)
botfather_token: "YOUR_BOTFATHER_TOKEN" #-> Insert your BOT FATHER TOKEN

# [en] REPORT DISABLE = false | REPORT ENABLE = true
# [pt_br] RELATÓRIO DESABILITADO = false | RELATÓRIO HABILITADO = true
enable_coin_report: true
enable_map_report: true
format_of_image: "jpg"
enable_emergency_call: false
